name: Create Release

on:
  push:
    branches: ["main"]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build-ui.yml
      - uses: ./.github/workflows/build-fw.yml
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-${{ github.run_number }}"
          prerelease: false
          files: |
            ./.pio/build/**/firmware_*.bin
            ./.pio/build/**/spiffs.bin
            ./.pio/project.checksum
